### ISSUE TITLE
Date issue when uploading new challenges

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/rocc-client-python#16]
From @tschaffter:

```
$ python push_challenges.py
Traceback (most recent call last):
  File "push_challenges.py", line 146, in <module>
    main()
  File "push_challenges.py", line 142, in main
    populate_db(api_client, json_dump)
  File "push_challenges.py", line 128, in populate_db
    add_challenge(challenge_api, challenge, person_ids)
  File "push_challenges.py", line 95, in add_challenge
    api.create_challenge(challenge=challenge)
  File "/mnt/c/Users/thoma/Documents/dev/rocc-client/roccclient/api/challenge_api.py", line 68, in create_challenge
    return self.create_challenge_with_http_info(challenge, **kwargs)  # noqa: E501
  File "/mnt/c/Users/thoma/Documents/dev/rocc-client/roccclient/api/challenge_api.py", line 158, in create_challenge_with_http_info
    return self.api_client.call_api(
  File "/mnt/c/Users/thoma/Documents/dev/rocc-client/roccclient/api_client.py", line 373, in call_api
    return self.__call_api(resource_path, method,
  File "/mnt/c/Users/thoma/Documents/dev/rocc-client/roccclient/api_client.py", line 192, in __call_api
    raise e
  File "/mnt/c/Users/thoma/Documents/dev/rocc-client/roccclient/api_client.py", line 185, in __call_api
    response_data = self.request(
  File "/mnt/c/Users/thoma/Documents/dev/rocc-client/roccclient/api_client.py", line 417, in request
    return self.rest_client.POST(url,
  File "/mnt/c/Users/thoma/Documents/dev/rocc-client/roccclient/rest.py", line 266, in POST
    return self.request("POST", url,
  File "/mnt/c/Users/thoma/Documents/dev/rocc-client/roccclient/rest.py", line 225, in request
    raise ApiException(http_resp=r)
roccclient.exceptions.ApiException: (500)
Reason: INTERNAL SERVER ERROR
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Content-Length': '122', 'Server': 'Werkzeug/1.0.1 Python/3.8.5', 'Date': 'Fri, 18 Dec 2020 04:12:40 GMT'})
HTTP response body: {
  "detail": "Parser must be a string or character stream, not datetime",
  "status": 500,
  "title": "Internal error"
```

**Comment by tschaffter** [comment]
Fixed in https://github.com/Sage-Bionetworks/rocc/issues/40
